package com.cowboyclearance.store.database;

import com.cowboyclearance.store.database.Inventory;
import com.cowboyclearance.store.database.Sale;
import com.cowboyclearance.store.database.User;

import java.math.BigDecimal;
import java.sql.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Utility class for SQLite operations.
 * Uses try-with-resources, PreparedStatements, and batch updates.
 */
public class SQLite {
    private static final String URL = "jdbc:sqlite:cowboy_clearance.sqlite";

    /**
     * Execute a SELECT query with parameters; return an open ResultSet.
     * Caller must process and close the ResultSet.
     */
    private static ResultSet executeQuery(Connection conn, String sql, Object... params) throws SQLException {
        PreparedStatement ps = conn.prepareStatement(sql);
        for (int i = 0; i < params.length; i++) {
            ps.setObject(i + 1, params[i]);
        }
        return ps.executeQuery();
    }

    /**
     * Execute an INSERT/UPDATE/DELETE with parameter binding.
     */
    private static void executeUpdate(Connection conn, String sql, Object... params) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            for (int i = 0; i < params.length; i++) {
                ps.setObject(i + 1, params[i]);
            }
            ps.executeUpdate();
        }
    }

    /**
     * Add a new user; ID is auto-generated by the database.
     */
    /*
    public static void addUser(User user) {
        System.out.println("Adding user " + user.getEmail());
        String sql = "INSERT INTO Users (Username, Password) VALUES (?, ?)";
        try (Connection conn = DriverManager.getConnection(URL);
             PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setString(1, user.getEmail());
            ps.setString(2, user.getPassword());
            ps.executeUpdate();

            // Capture generated ID and set into model
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    user.setId(keys.getInt(1));
                }
            }
        } catch (SQLException e) {
            e.printStackTrace(System.err);
        }
    }
     */

    /**
     * Add a new user; ID is auto-generated by the database.
     * New users are non-admins by default.
     */
    public static void addUser(User user) {
        System.out.println("Adding user: " + user.getEmail());
        String sql = "INSERT INTO Users (Username, Password, IsAdmin) VALUES (?, ?, 0)";
        try (Connection conn = DriverManager.getConnection(URL);
             PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setString(1, user.getEmail());
            ps.setString(2, user.getPassword());
            ps.executeUpdate();

            // Capture generated ID and set into model
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    user.setId(keys.getInt(1));
                }
            }
        } catch (SQLException e) {
            e.printStackTrace(System.err);
        }
    }


    /**
     * Fetch a user by email; return null if not found.
     */
    public static User getUser(String email) {
        String sql = "SELECT UserID, Username, Password, IsAdmin FROM Users WHERE Username = ?";
        try (Connection conn = DriverManager.getConnection(URL);
             ResultSet rs = executeQuery(conn, sql, email)) {

            if (rs.next()) {
                User user = new User();
                user.setId(rs.getInt("Id"));
                user.setEmail(rs.getString("Username"));
                user.setPassword(rs.getString("Password"));
                user.setAdmin(rs.getBoolean("IsAdmin"));
                return user;
            }
        } catch (SQLException e) {
            e.printStackTrace(System.err);
        }
        return null;
    }

    /**
     * Promote a user to administrator.
     */
    public static void makeAdmin(User user) {
        String sql = "UPDATE Users SET IsAdmin = 1 WHERE Username = ?";
        try (Connection conn = DriverManager.getConnection(URL)) {
            executeUpdate(conn, sql, user.getEmail());
        } catch (SQLException e) {
            e.printStackTrace(System.err);
        }
    }

    /**
     * Insert a sale and its sale-items in a single transaction.
     * Sale.id is populated from the generated keys.
     */
    public static void addSale(User user, Sale sale, int[] itemIds) {
        String saleSql =
                "INSERT INTO Sales (UserID, PurchaseDate, Subtotal, Tax, Shipping, FinalTotal) VALUES (?, ?, ?, ?, ?, ?)";
        String itemSql = "INSERT INTO SalesInventoryItem (SalesID, ItemID) VALUES (?, ?)";

        try (Connection conn = DriverManager.getConnection(URL)) {
            conn.setAutoCommit(false);

            // Insert sale record
            try (PreparedStatement psSale = conn.prepareStatement(saleSql, Statement.RETURN_GENERATED_KEYS)) {
                psSale.setInt(1, user.getId());
                psSale.setString(2, sale.getDate());
                psSale.setInt(3, sale.getSubtotal());
                psSale.setInt(4, 0);               // tax placeholder
                psSale.setString(5, sale.getShipping());
                psSale.setInt(6, sale.getTotal());
                psSale.executeUpdate();

                try (ResultSet keys = psSale.getGeneratedKeys()) {
                    if (keys.next()) {
                        sale.setId(keys.getInt(1));
                    }
                }
            }

            // Batch insert items
            try (PreparedStatement psItem = conn.prepareStatement(itemSql)) {
                for (int itemId : itemIds) {
                    psItem.setInt(1, sale.getID());
                    psItem.setInt(2, itemId);
                    psItem.addBatch();
                }
                psItem.executeBatch();
            }

            conn.commit();
        } catch (SQLException e) {
            e.printStackTrace(System.err);
        }
    }

    /**
     * Retrieve all sales for a user.
     */
    public static List<Sale> salesReport(User user) {
        List<Sale> report = new ArrayList<>();
        String sql =
                "SELECT SalesID, PurchaseDate, Subtotal, Tax, Shipping, FinalTotal FROM Sales WHERE UserID = ?";

        try (Connection conn = DriverManager.getConnection(URL);
             ResultSet rs = executeQuery(conn, sql, user.getId())) {

            while (rs.next()) {
                Sale sale = new Sale();
                sale.setId(rs.getInt("SalesID"));
                sale.setDate(rs.getString("PurchaseDate"));
                sale.setSubtotal(rs.getInt("Subtotal"));
                sale.setShipping(rs.getString("Shipping"));
                sale.setTotal(rs.getInt("FinalTotal"));
                report.add(sale);
            }
        } catch (SQLException e) {
            e.printStackTrace(System.err);
        }
        return report;
    }

    /**
     * Retrieve inventory list; thread-safe list wrapper.
     */
    public static List<Inventory> getInventory() {
        List<Inventory> list = Collections.synchronizedList(new ArrayList<>());
        String sql = "SELECT ItemID, ItemName, Price, Description, Image FROM Inventory";

        try (Connection conn = DriverManager.getConnection(URL);
             ResultSet rs = executeQuery(conn, sql)) {

            while (rs.next()) {
                Inventory inv = new Inventory();
                inv.setId(rs.getInt("ItemID"));
                inv.setName(rs.getString("ItemName"));
                inv.setPrice(rs.getInt("Price"));
                inv.setDescription(rs.getString("Description"));
                inv.setImage(rs.getString("Image"));
                list.add(inv);
            }
        } catch (SQLException e) {
            e.printStackTrace(System.err);
        }
        return list;
    }

    /**
     * Lookup a shipping rate column by name. Column values are integers representing cents.
     */
    public static int getShippingRate(String column) throws SQLException {
        String sql = "SELECT " + column + " FROM ShippingInfo";
        try (Connection conn = DriverManager.getConnection(URL);
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(sql)) {
            return rs.getInt(column);
        }
    }
}